// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://venrrebvecimfghltijm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbnJyZWJ2ZWNpbWZnaGx0aWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTAwMDYsImV4cCI6MjA2Njk4NjAwNn0.B2efza324lVdNcWvottKpxD41swV5oDJbhFs_N1n0pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});